import React from 'react'
import './term.css'

export default function Terms() {
  return (
    <div className="terms-container-1">
    <h1 className="terms-title">Terms & Condition</h1>
    
    <div className="terms-section-1">
      <h2 className="terms-subtitle"></h2>
      <p>
      This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures
      </p>
      
    </div>
    
    <div className="terms-section-1">
      <h3 className="terms-subsection-title"></h3>
      <p>
      This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <b> https://www.sptiwari.in/pricing </b> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
      </p>
    </div>
    
    <div className="terms-section-1">
      <h2 className="terms-subtitle"></h2>
     <p>
     The Platform is owned by <b>SURYA PRAKASH TIWARI,</b>  a proprietary firm incorporated under the <b>Udyam (MSME)</b> with its registered office at <b> D 206 BRAVE HEART RAJ NAGAR EXTENSION GHAZIABAD UP 201017 ,Ghaziabad ,India </b> (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our')..
     </p>
    </div>

    <div className="terms-section-1">
      <h2 className="terms-subtitle"></h2>
     <p>
     	Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates..
     </p>

     <p>
     For the purpose of these Terms of Use, wherever the context so requires ‘you’, 'your' or ‘user’ shall mean any natural or legal person who has agreed to become a user/buyer on the Platform..
     </p>

     <p><b>
     ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING..
     </b>
     </p>
    </div>

    <div className="terms-section-1">
      <h2 className="terms-subtitle"></h2>
      <p><b>The use of Platform and/or availing of our Services is subject to the following Terms of Use</b></p>
     <p>
      1. To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform..
     </p>

     <p>
     2.	Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law..
     </p>

     <p>
     3. Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements..
     </p>

     <p>
     4. The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics
     </p>

     <p>
      5.	You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws..
     </p>

     <p>
     6.	You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you
     </p>

     <p>
     7.	You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information..
     </p>

     <p>
     8.	You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services..
     </p>

     <p>
     9.	You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
     </p>

     <p>
     10.	Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event..
     </p>

     <p>
     11.	These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India..
     </p>

     <p>
     12.	All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <b>Ghaziabad</b> and  <b>Uttar Pradesh</b>.
     </p>

     <p>
     13.	All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website
     </p>
    </div>

  </div>
  )
}


// General
// This page provides the terms and conditions for use of the www.sptiwari.in / www.workshop.sptiwari.inoperated by legal entity ‘Mansun Consultancy Private Limited’ - website and pages accessible there from, herein after referred to as the “Site” and the services contained within. By using the Site or downloading information from the Site, the user (You) agree to the terms and conditions listed here. This Agreement applies to users(s) if users(s) are visitors, registered- free or paid user(s) who access the website for any purpose.

// It also applies to any legal entity which may be represented by you.

// Account Deletion

// When you delete your account you will receive a confirmation email stating that your account has been deleted. Once you delete your account, it is not possible to get it back. We do not offer refunds, even if the account has been deleted.

// Disclaimer
// Dispute Resolution and Jurisdiction

// In the event that the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the Mansun Consultancy Pvt Ltd, and the award passed by such sole arbitrator will be valid and binding on both Parties. The Parties shall bear their own costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be in Chennai, India.

// The Parties expressly agree that the Terms, Policy and any other agreements entered into between the Parties are governed by the laws, rules, and regulations of India, and that the Courts at Chennai, India, shall have exclusive jurisdiction over any disputes arising between the Parties.

// GRIEVANCE OFFICER

// In accordance with Information Technology Act 2000 and rules made thereunder, the name and contact details of the Grievance Officer are provided below:

// Anuja Johnson

// anuja@mansunconsultancy.com

// Thank you for using our Services. We hope you find the services helpful, informative, and convenient to use. If you have any questions regarding these Terms and Conditions, please contact us by email at support@mansunconsultancy.com

