import React from 'react'
import './term.css'

export default function Terms() {
  return (
    <div>
      <div class="container">
    <h1>Terms and Conditions</h1>
    <h2><span class="section-number">1.</span> Powerofstocks Terms and Conditions</h2>
    <p><span class="section-number">1.1</span> These Terms & Conditions are legally binding between the person accessing the website or downloading the app (which expression shall include its successors and assigns).</p>
    <p><span class="section-number">1.2</span> By accessing this website or downloading this application you shall be giving your consent to defined terms & conditions & will be bound by existing Information technology Act 2000/2008 & Rules defined and other law as applicable in India.</p>
    <p><span class="section-number">1.3</span> Acceptance of the General Terms and Conditions and Privacy Policy is mandatory in order to use the services provided by us. The use of services provided by us implies/denotes full acceptance of the General Terms and Conditions and privacy policy.</p>
    <p><span class="section-number">1.4</span> These Terms constitute an 'electronic record' within the meaning of the applicable law (including the Information Technology Act, 2000, IT Act 2008 Amendment) and is generated by a computer system and does not require any physical or digital signatures.</p>
  </div>
    </div>
  )
}
